#!/usr/bin/env bash
#
# gen-manifests.sh - Generate Claude Code manifests from Cursor plugin manifests.
#
# This fork exists so Claude Code can consume plugins from cursor/plugins, which
# only ships Cursor manifests (.cursor-plugin/plugin.json). Rather than hand-maintain
# a parallel set of Claude manifests that drift on every upstream release, this script
# derives them. Run it after every upstream merge (the sync-upstream workflow does).
#
# Generated (tracked in git, this fork only):
#   .claude-plugin/marketplace.json
#   <plugin>/.claude-plugin/plugin.json   for each plugin in PLUGINS

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Plugins exposed to Claude Code. Add a directory name here to publish another one.
PLUGINS=(pstack)

MARKETPLACE_OWNER_NAME="Pierrick Turelier"
MARKETPLACE_OWNER_URL="https://github.com/PierrickGT"

gen_plugin_manifest() {
	local plugin="$1"
	local cursor_manifest="$REPO_ROOT/$plugin/.cursor-plugin/plugin.json"
	local claude_manifest="$REPO_ROOT/$plugin/.claude-plugin/plugin.json"

	if [[ ! -f "$cursor_manifest" ]]; then
		echo "error: $cursor_manifest not found" >&2
		return 1
	fi

	mkdir -p "$(dirname "$claude_manifest")"

	# Claude Code auto-discovers skills/, agents/, commands/ and hooks/ inside the
	# plugin directory, so the Cursor-specific path fields are deliberately dropped.
	jq --sort-keys '{
		name,
		description,
		version,
		author,
		homepage,
		license,
		keywords
	} | with_entries(select(.value != null))' "$cursor_manifest" >"$claude_manifest"

	echo "generated $plugin/.claude-plugin/plugin.json ($(jq -r .version "$claude_manifest"))"
}

gen_marketplace_manifest() {
	local entries="[]"

	for plugin in "${PLUGINS[@]}"; do
		local claude_manifest="$REPO_ROOT/$plugin/.claude-plugin/plugin.json"
		entries=$(jq --argjson entries "$entries" --arg source "./$plugin" \
			'$entries + [{name, source: $source, description, version, author, homepage, license, keywords}
			 | with_entries(select(.value != null))]' "$claude_manifest")
	done

	mkdir -p "$REPO_ROOT/.claude-plugin"
	jq --sort-keys -n \
		--arg ownerName "$MARKETPLACE_OWNER_NAME" \
		--arg ownerUrl "$MARKETPLACE_OWNER_URL" \
		--argjson plugins "$entries" \
		'{
			name: "pstack",
			owner: {name: $ownerName, url: $ownerUrl},
			metadata: {
				description: "Claude Code view of selected plugins from cursor/plugins. Manifests are generated by .claude-sync/gen-manifests.sh; plugin content is unmodified upstream."
			},
			plugins: $plugins
		}' >"$REPO_ROOT/.claude-plugin/marketplace.json"

	echo "generated .claude-plugin/marketplace.json (${#PLUGINS[@]} plugin(s))"
}

for plugin in "${PLUGINS[@]}"; do
	gen_plugin_manifest "$plugin"
done

gen_marketplace_manifest
